sql_lite:
  outputs:

    dev:
      type: sqlite
      threads: 1
      database: <database name>
      schema: 'main'
      schemas_and_paths:
        main: '/my_project/data/etl.db'
      schema_directory: '/my_project/data'
      extensions:
        - '/path/to/sqlite-digest/digest.so'

    prod:
      type: sqlite
      threads: 1
      database: main
      schema: 'main'
      schemas_and_paths:
        main: '<current_dir>/dbt_with_sqlite3/dataset/data_models.db'
      schema_directory: '<current_dir>/dbt_with_sqlite3/dataset/'


  target: prod