
version: 2
models:
  - name: vw_gold_medal_count_by_athlete_2
    description: "Model to find out the >= 3 gold medal count"
    columns:
      - name: name
        description: "The athelete Name"
        tests:
          - unique
          - not_null
          - not_empty
  - name: vw_region_wise_avg_height_2
    description: "Model to find out the average height by region"
    columns:
      - name: region
        description: "region column name"
        tests:
          - unique
          - not_null
          - not_empty        

