
version: 2

models:
  - name: staging_countries_2
    description: "Staging data models for countries data"
    columns:
      - name: country_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - not_empty      
  - name: staging_athletes_2
    description: "Staging data models for athelets data"
    columns:
      - name: athlete_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null 
          - not_empty       
  - name: staging_games_2
    description: "Staging data models for games data"
    columns:
      - name: sport_name
        description: "Not null sport name"
        tests:
          - not_null  
          - not_empty              
